/*
 *
 *       Created by tux on 13.03.2024.
 *       ________   _______  ____ ____  _______  ____ ____
 *      │----R---\ /---A---\ ----Y---- /---O---\│----N----\
 *      │         │         │    │    │         │         │
 *      │    ^    │    ^    │    │    │    ^    │    ^    │
 *      │    │    │    │    │    │    │    │    │    │    │
 *      │    │    │    │    │    │    │    │    │    │    │
 *      │    ┼    │    ┼    │    ┼    │    ┼    │    │    │
 *      │        (          \         │    │    │    │    │
 *      │    ^    │    ^    │)        │    │    │    │    │
 *      │    │    │    │    /         │    v    │    │    │
 *      │    │    │    │    │        /│         │    │    │
 *      │────│────│────│────│───────/  \_______/│____│____│
 *
 *      RayOn - simple rig to play with rays
 *
 *      ThreadSafeQueue - queue that used to store rendering tasks and rendering results
 *      generated by ChatGPT so I will have to review it
 *
 */

#ifndef RAYLIB_TEMPLATE_THREADSAFEQUEUE_H
#define RAYLIB_TEMPLATE_THREADSAFEQUEUE_H


#include <mutex>
#include <queue>
#include <condition_variable>


template<typename T>
class ThreadSafeQueue {
private:
    std::queue<T> queue;
    mutable std::mutex m;
    std::condition_variable cv;

    bool is_finished = false;

public:
    ThreadSafeQueue() = default;
    ThreadSafeQueue(const ThreadSafeQueue& other) = delete;
    ThreadSafeQueue& operator=(const ThreadSafeQueue& other) = delete;

    void push(T value) {
        std::lock_guard<std::mutex> lock(m);
        queue.push(std::move(value));
        cv.notify_one();
    }

    bool try_pop(T& value) {
        std::lock_guard<std::mutex> lock(m);
        if (queue.empty()) {
            return false;
        }
        value = std::move(queue.front());
        queue.pop();
        return true;
    }

    bool empty() const {
        std::lock_guard<std::mutex> lock(m);
        return queue.empty();
    }

    void finish() {
        std::lock_guard<std::mutex> lock(m);
        is_finished = true;
        cv.notify_all();
    }

    bool wait_and_pop(T& value) {
        std::unique_lock<std::mutex> lock(m);
        cv.wait(lock, [this] { return !queue.empty() || is_finished; });
        if (queue.empty()) return false;
        value = std::move(queue.front());
        queue.pop();
        return true;
    }

    bool finished() const {
        std::lock_guard<std::mutex> lock(m);
        return is_finished && queue.empty();
    }
};


#endif //RAYLIB_TEMPLATE_THREADSAFEQUEUE_H
